# agent/conflict_resolver/__main__.py
"""CLI entry point: python -m agent.conflict_resolver.

Exit codes:
  0  — resolved cleanly, commit produced, harness should push.
  10 — model exited with conflicts unresolved; harness should comment + stop.
  11 — manager rejected after all feedback rounds; harness should comment + stop.
  12 — test_command validation failed (Phase 4, future); reserved.
  99 — budget exhausted; harness should label + comment.
  1  — SDK error or other unrecoverable problem; harness should comment + stop.

The harness (resolve-conflicts.sh) interprets these and posts the appropriate
PR comment / label combination.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import logging
import os
import subprocess
import sys
from pathlib import Path

from app.database import async_session
from agent.conflict_resolver.budget import (
    record_attempt_finish,
    record_attempt_start,
    tokens_used_in_window,
)
from agent.conflict_resolver.markers import file_has_conflicts, parse_conflict_markers
from agent.conflict_resolver.prompts import AdvisoryTier, build_resolver_prompt
from agent.conflict_resolver.sdk_runner import run_resolver

logger = logging.getLogger(__name__)


def _list_conflicted_files(workspace: str) -> list[str]:
    """git diff --name-only --diff-filter=U inside workspace."""
    result = subprocess.run(
        ["git", "-C", workspace, "diff", "--name-only", "--diff-filter=U"],
        capture_output=True, text=True, check=False, timeout=10,
    )
    return [p for p in result.stdout.splitlines() if p.strip()]


def _conflict_region_line_count(workspace: str, conflicted_files: list[str]) -> int:
    """Sum lines inside <<<<<<< ... >>>>>>> regions across all files.

    This is the right proxy for "how much disagreement is there?" — using the
    file's full size massively over-counts when one tiny conflict lives in a
    large file (review finding #2).
    """
    total = 0
    for fp in conflicted_files:
        full = Path(workspace) / fp
        try:
            text = full.read_text()
        except (OSError, UnicodeDecodeError):
            continue
        for region in parse_conflict_markers(text):
            total += len(region.ours_lines) + len(region.theirs_lines)
    return total


def _compute_advisory_tiers(
    workspace: str,
    conflicted_files: list[str],
    *,
    pr_age_days: int | None,
    has_prior_attempt: bool,
) -> set[AdvisoryTier]:
    """Inspect the worktree to decide which advisory tiers apply."""
    tiers: set[AdvisoryTier] = set()
    if len(conflicted_files) > 10:
        tiers.add(AdvisoryTier.MANY_FILES)
    if _conflict_region_line_count(workspace, conflicted_files) > 500:
        tiers.add(AdvisoryTier.LARGE_DIFF)
    if pr_age_days is not None and pr_age_days > 7:
        tiers.add(AdvisoryTier.STALE_PR)
    if has_prior_attempt:
        tiers.add(AdvisoryTier.PRIOR_ATTEMPT)
    return tiers


def _write_handoff_report(
    *,
    workspace: str,
    branch: str,
    base_branch: str,
    run_id: str | None,
) -> None:
    """Write `.claude-employee-report-conflict-resolver.json` so the existing
    manager-review pipeline picks up the resolver's commit.

    Without this, run-manager.sh's `any_reports` check (the same one PR #332
    fixed for orchestrator-side teammates) finds nothing and skips manager
    review — exactly the failure mode review finding #4 flagged. We mirror
    PR #332's synthesizer shape: branch, base_branch, files_changed, commits,
    synthesized_by="conflict-resolver".
    """
    try:
        commits_proc = subprocess.run(
            ["git", "-C", workspace, "log", "--format=%H", f"{base_branch}..HEAD"],
            capture_output=True, text=True, check=False, timeout=10,
        )
        commits = [c for c in commits_proc.stdout.splitlines() if c.strip()]

        files_proc = subprocess.run(
            ["git", "-C", workspace, "diff", "--name-only", f"{base_branch}..HEAD"],
            capture_output=True, text=True, check=False, timeout=10,
        )
        files = [f for f in files_proc.stdout.splitlines() if f.strip()]

        report = {
            "status": "success",
            "branch": branch,
            "base_branch": base_branch,
            "files_changed": files,
            "commits": commits,
            "tests_run": False,
            "tests_passed": False,
            "confidence": 0.5,
            "confidence_reasoning": (
                "Synthesized by conflict resolver from worktree git state. "
                "Conflict markers were resolved and a commit was produced; "
                "tests/quality were not verified by the resolver itself."
            ),
            "notes": (
                "This report was generated by the conflict resolver as a "
                "hand-off so the manager review pipeline can gate the "
                "resolution before push."
            ),
            "synthesized_by": "conflict-resolver",
            "run_id": run_id,
        }
        path = Path(workspace) / ".claude-employee-report-conflict-resolver.json"
        path.write_text(json.dumps(report, indent=2))
        logger.info(
            "Wrote handoff report at %s (%d commit(s), %d file(s))",
            path, len(commits), len(files),
        )
    except Exception as exc:  # pragma: no cover — defensive
        logger.warning("Failed to write conflict-resolver handoff report: %s", exc)


async def _amain(args: argparse.Namespace) -> int:
    async with async_session() as db:
        used = await tokens_used_in_window(db, branch=args.branch, window_hours=24)
    if used >= args.budget:
        logger.warning(
            "Budget exhausted for %s: used=%d, budget=%d", args.branch, used, args.budget,
        )
        return 99

    conflicted = _list_conflicted_files(args.workspace)
    if not conflicted:
        # Nothing to do — should be caught by Phase 1, but defensive.
        logger.info("No conflicted files in %s; nothing to resolve", args.workspace)
        return 0

    tiers = _compute_advisory_tiers(
        args.workspace, conflicted,
        pr_age_days=args.pr_age_days,
        has_prior_attempt=False,  # set by caller in future iterations
    )

    async with async_session() as db:
        attempt_id = await record_attempt_start(
            db,
            branch=args.branch,
            repo=args.repo,
            triggered_by=args.triggered_by,
            run_id=args.run_id,
            pr_number=args.pr_number,
        )

    prompt = build_resolver_prompt(
        branch=args.branch,
        base_branch=args.base_branch,
        conflicted_files=conflicted,
        advisory_tiers=tiers,
        prior_failure_reason=None,
    )

    outcome = await run_resolver(
        prompt=prompt,
        workspace=args.workspace,
        run_id=args.run_id or f"conflict-{attempt_id}",
        model=args.model,
        max_turns=args.max_turns,
    )

    if outcome.error:
        async with async_session() as db:
            await record_attempt_finish(
                db, attempt_id=attempt_id,
                phase_reached="llm", outcome="error",
                tokens_input=outcome.tokens_input,
                tokens_output=outcome.tokens_output,
                tokens_total=outcome.tokens_total,
                model_used=args.model,
                error_detail=outcome.error,
            )
        return 1

    # Re-check whether conflicts remain; if so, the model didn't actually
    # finish — distinct outcome from "tests_failed" (Phase 4 validation).
    # The harness still has feedback rounds to spend in subsequent
    # invocations — for v1 we treat this as one attempt and let the
    # bash harness re-invoke us.
    remaining = _list_conflicted_files(args.workspace)
    if remaining:
        async with async_session() as db:
            await record_attempt_finish(
                db, attempt_id=attempt_id,
                phase_reached="llm", outcome="unresolved",
                tokens_input=outcome.tokens_input,
                tokens_output=outcome.tokens_output,
                tokens_total=outcome.tokens_total,
                model_used=args.model,
                error_detail=outcome.last_text or "model exited with conflicts unresolved",
            )
        return 10

    # Resolution succeeded — write the handoff report so the existing
    # manager-review pipeline picks up the resolver's commit. Without this,
    # run-manager.sh:2826's `any_reports` check finds nothing and skips
    # review (same failure mode PR #332 fixed for orchestrator-side teammates).
    _write_handoff_report(
        workspace=args.workspace,
        branch=args.branch,
        base_branch=args.base_branch,
        run_id=args.run_id,
    )

    async with async_session() as db:
        await record_attempt_finish(
            db, attempt_id=attempt_id,
            phase_reached="llm", outcome="resolved",
            tokens_input=outcome.tokens_input,
            tokens_output=outcome.tokens_output,
            tokens_total=outcome.tokens_total,
            model_used=args.model,
        )
    return 0


def main() -> None:
    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s %(name)s %(levelname)s %(message)s",
    )
    parser = argparse.ArgumentParser(description="Conflict resolver — Phase 3")
    parser.add_argument("--workspace", required=True, help="conflicted worktree path")
    parser.add_argument("--branch", required=True)
    parser.add_argument("--base-branch", required=True)
    parser.add_argument("--repo", required=True, help="owner/name")
    parser.add_argument("--pr-number", type=int, default=None)
    parser.add_argument("--pr-age-days", type=int, default=None)
    parser.add_argument("--run-id", default=None)
    parser.add_argument("--triggered-by", choices=["pre_pr", "at_merge"], required=True)
    parser.add_argument("--model", default=os.environ.get("CONFLICT_MODEL", "claude-opus-4-7"))
    parser.add_argument("--max-turns", type=int, default=30)
    parser.add_argument("--budget", type=int, default=200_000, help="rolling 24h token cap")
    args = parser.parse_args()

    sys.exit(asyncio.run(_amain(args)))


if __name__ == "__main__":
    main()
